# Generated by Django 2.0 on 2021-04-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(default='')),
                ('dest', models.TextField(default='')),
                ('busNo', models.TextField(default='')),
            ],
        ),
    ]
